version: '3'
services:
 weatherapi:
  build: .
  ports: 
  - "8080:80"
  - "8081:443"
  envoriment:
   ASPNETCORE_URLS: "https://+;http://+"
   ASPNETCORE_HTTPS_PORT: "8081"
   ASPNETCORE_ENVIRONMENT: "Development"


